### ISSUE TITLE
postcss issue

### ISSUE THREAD

**Issue by smartapant** [OnsenUI/vue-cordova-webpack#5]
Hi!

I'm trying to use postcss theming like it's done here https://github.com/OnsenUI/vue-onsenui-kitchensink

The problem - postcss seem not to work as i'm getting not all of the  Onsen's styles (especially @apply doesn't work)

Could you please point out what shall i change in webpack to make it work?

**Comment by frandiox** [comment]
@smartapant Did you manage to do it in the end? `apply` spec is now deprecated so it will be remove from `postcss-cssnext` after version 3, but it should be fine until that version. Maybe you can try [`postcss-apply`](https://github.com/pascalduez/postcss-apply). In any case, you can simply use the theme previewer that you have in `node_modules/onsenui/css-components-src/` to generate your custom theme. There is a [guide here](https://onsen.io/v2/guide/theming.html#theme-customization).
