### ISSUE TITLE
Choppy scrolling on Android caused by `ons-swiper-blocker`?

### ISSUE THREAD

**Issue by levibeach** [OnsenUI/vue-cordova-webpack#6]
I noticed that if I have content in a `v-ons-tabbar` that scrolled on my Android device that it was running very "choppy". After a couple of hours of trying to figure out why, I noticed that there is an empty element with a class of `ons-swiper-blocker` sitting on the page. Not sure what it doesn't (haven't dug into the component JS to find out), but hiding it with CSS (`display: none;`) fixed the scroll issue and now the tabbed content scrolls buttery smooth.

Any thoughts as to what's going on here?

**Comment by frandiox** [comment]
@levibeach Hi! The `ons-swiper-blocker` is blocking clicks while swiping. It is necessary for Chrome but I think it can be omitted on Android. However, I haven't seen any scrolling issue on Android with it. What Android version were you using? Does it happen with a simple tabbar or you have custom code?

**Comment by levibeach** [comment]
I tested it out on Android 6.0.1 and 7.0 using a standard tabbar which had a custom font applied to the labels. In both cases the scrolling was running somewhere between 12 - 24 fps until I hid the `ons-swiper-blocker`

**Comment by frandiox** [comment]
@levibeach Can you try `onsenui@2.8.1`? I think it should be fixed there.

**Comment by levibeach** [comment]
@frandiox works like a charm! Thanks!
