### ISSUE TITLE
Onsen CSS Bug

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/vue-cordova-webpack#8]
When running this with npm run dev I get the following error:
Gradient has outdated direction syntax. Replace 'cover' to 'farthest-corner'

This should be easily fixed by replacing all occurrences of 'cover' with 'farthest-corner'

Edit: just checked it is fixed in OnsenUI main repo but 'vue init OnsenUI/vue-cordova-webpack hello-world' load an older version I guess?

**Comment by d3orn** [comment]
This should fix it

**Comment by frandiox** [comment]
@d3orn Yep, I fixed that a while ago but didn't update the version in the template. Thanks for the PR!
